### ISSUE TITLE
Add support to install ansible collection as tarball

### ISSUE THREAD

**Issue by pabelanger** [ansible/ansible-builder#122]
In some cases, we want to be able to install a collection tarball from the local file system. This could be before we don't have access to galaxy or we are testing an unreleased version of code.

We do this today by not using a requirement file, and use the CLI directly
```
ansible-galaxy collection install  vyos-vyos-1.1.1-dev2.tar.gz ansible-netcommon-1.4.2-dev1.tar.gz
```

**Comment by AlanCoding** [comment]
I was kind of excited about the download command, demo with awx-ee:

```
ansible-galaxy collection download -r _build/requirements.yml -p alan
```

produces

```
$ tree alan/
alan/
├── amazon-aws-1.3.0.tar.gz
├── ansible-netcommon-1.4.1.tar.gz
├── ansible-posix-1.1.1.tar.gz
├── awx-awx-16.0.0.tar.gz
├── azure-azcollection-1.3.1.tar.gz
├── community-kubernetes-1.1.1.tar.gz
├── community-vmware-1.6.0.tar.gz
├── google-cloud-1.0.1.tar.gz
├── openstack-cloud-1.0.1.tar.gz
├── ovirt-ovirt-1.2.5.tar.gz
├── requirements.yml
└── theforeman-foreman-1.5.1.tar.gz

0 directories, 12 files
```

```
$ cat alan/requirements.yml 
collections:
- name: awx-awx-16.0.0.tar.gz
  version: 16.0.0
- name: azure-azcollection-1.3.1.tar.gz
  version: 1.3.1
- name: amazon-aws-1.3.0.tar.gz
  version: 1.3.0
- name: theforeman-foreman-1.5.1.tar.gz
  version: 1.5.1
- name: google-cloud-1.0.1.tar.gz
  version: 1.0.1
- name: openstack-cloud-1.0.1.tar.gz
  version: 1.0.1
- name: community-vmware-1.6.0.tar.gz
  version: 1.6.0
- name: ovirt-ovirt-1.2.5.tar.gz
  version: 1.2.5
- name: community-kubernetes-1.1.1.tar.gz
  version: 1.1.1
- name: ansible-posix-1.1.1.tar.gz
  version: 1.1.1
- name: ansible-netcommon-1.4.1.tar.gz
  version: 1.4.1
```

There are likely to be multiple ways to use this feature, and I would love if we had some way to support installing from the requirements file from `download` like this.

**Comment by AlanCoding** [comment]
I was going in the direction of a `requirements.yml` file here, but the issue mentions giving CLI args to the install command. We need to think carefully about what we want to support here, and I need to start with the Ansible code base for that.

This is the blurb that processes CLI args (as opposed to requirements file) for `ansible-galaxy collection install`:

https://github.com/ansible/ansible/blob/e7dee73774b0b436551e4993ba917eec1e03af2d/lib/ansible/cli/galaxy.py#L745-L755

```python
            requirements = {'collections': [], 'roles': []}
            for collection_input in collections:
                requirement = None
                if os.path.isfile(to_bytes(collection_input, errors='surrogate_or_strict')) or \
                        urlparse(collection_input).scheme.lower() in ['http', 'https'] or \
                        collection_input.startswith(('git+', 'git@')):
                    # Arg is a file path or URL to a collection
                    name = collection_input
                else:
                    name, dummy, requirement = collection_input.partition(':')
                requirements['collections'].append((name, requirement or '*', None, None))
```

The partitioning works as so:

```python
>>> 'awx.awx:15.0.0'.partition(':')
('awx.awx', ':', '15.0.0')
```

In either case, it is constricting a dictionary in the same format as a `requirements.yml` file from the args. There are 2 code branches for each item, either it is interpreted as a "thing", and if not, then it is interpreted as a collection name (and optional version specifier). We can write out a precedence for what things it allows:

 - A file location that exists on the computer
 - A SCM address either due to `https` or `git+` type markers
 - Name for Galaxy / Automation Hub (name, version, scm_type, some more parameters)

I think the actual install is implemented [here](https://github.com/ansible/ansible/blob/e7dee73774b0b436551e4993ba917eec1e03af2d/lib/ansible/galaxy/collection/__init__.py#L251-L254), which is a bit simplified to: Is it a file? Install it as a file. Otherwise, install as SCM.

Granted, I don't know how this system manages to support patterns... which would be a major challenge for us.

----

What does this tell us for `ansible-builder`? Actually it tells us something very useful - that we are safe to apply the `os.path.isfile` test. That is all that _we_ need for an arg-type input (Ansible itself will distinguish SCM vs name, we don't care), with the very important nuance that this is relative to the definition file.

If it is a file, we need to `ADD` it like we do other things.

https://github.com/ansible/ansible-builder/blob/4118d93c66c9b27fc8fb5223d2b04ca4e54dadc7/ansible_builder/steps.py#L42

A concern here is that we don't want to do any more moves than we need. I don't have any solution, other than just documenting that people put things in the `_build` folder. Even that might need some touchup work.

**Comment by AlanCoding** [comment]
Closing as implemented
