### ISSUE TITLE
introspect.py should move into ansible-runner image

### ISSUE THREAD

**Issue by pabelanger** [ansible/ansible-builder#150]
We should move introspect.py into ansible-runner, rather then having every EE repo container a copy of it.

This might take a bit of work, given we hardcode some 'execution-environment' filenames / variables. But, not impossible.

**Comment by AlanCoding** [comment]
Is this just about introspect, or about getting rid of the 2-phase builds completely? The introspect script can easily be used on its own, but we do additional processing of its output which would need to be moved into the introspect script in order to get rid of the 2-phase system. Also, the introspect script would need to write the files on its own - this is functionality that we used to have but we removed.

https://github.com/ansible/ansible-builder/blob/c703300ecf597d939ac9ca79d3f10ab3dd0fbd64/ansible_builder/introspect.py#L216-L219

So by passing a destination location to write the combined `bindep.txt` file to, we avoid the need to have anything done _outside_ of the container. Right now, we read introspect output, sanitize the data, write it and then `ADD` it in another layer. We can add options like `--write-bindep` back in easily, but it's not the full picture.

https://github.com/ansible/ansible-builder/blob/4f9ee1c7eb12f2f5cf0d8e27565ca187474435a8/ansible_builder/requirements.py#L20

`sanitize_requirements` is done after the main `ansible-builder` process reads from the introspect output.

Even if we do that, I'm not sure if the ansible-runner image would be the best place, because it is tied to the ansible-builder version.

I'm not sure if this is relevant or not, but I want to point out that the Galaxy importer imports the introspect module from ansible-builder:

https://github.com/ansible/galaxy-importer/blob/ed96acbf660102eb5ebef26f857abece584ae525/galaxy_importer/utils/execution_environment.py#L18

But of course that assumes you have installed ansible-builder.

**Comment by pabelanger** [comment]
The main reason, was to avoid having multiple copies of introspect.py with in each git repo for an EE.  You can see:

https://github.com/ansible/network-ee/blob/main/_build/introspect.py
https://github.com/ansible/awx-ee/blob/devel/_build/introspect.py

Given that file isn't dynamically generated, I think it's better to store it inside a layer.  I poked around, and figured ansible-runner could be a place, as you say it might not be the best.

Regarding 2-phase builds, I think there is a story their to remove them. But know there is a history as to why.  I can open that into another PR, or we could rename this.

**Comment by AlanCoding** [comment]
Gotcha, to paraphrase, this is part of the goal of minimizing the content in the `_build` folder.

**Comment by pabelanger** [comment]
Ya, I think that would be fair.  Specific to introspect.py, I think there is a better way to manage that file, then it duplicated in a lot of repos.

**Comment by AlanCoding** [comment]
Hold on, we _don't_ put `introspect.py` in the image. Like, at all.

https://github.com/ansible/ansible-builder/blob/b40012151ff52ee29f5c32b2b9257abe0984c19e/ansible_builder/main.py#L92

We mount the build context folder.

So... just don't move it to the build context in the first place. Instead of mounting that folder, mount whatever folder the original `introspect.py` happens to be in. This is minor and probably mostly trivial.

**Comment by pabelanger** [comment]
++

**Comment by AlanCoding** [comment]
We didn't do exactly what the original idea was, but we accomplished the goal of getting rid of the need for `introspect.py`.

I'll put up a PR to awx-ee soon with the changes this causes
