### ISSUE TITLE
ansible-builder introspect --sanitize removes yamllint and ansible-lint from requirements.txt

### ISSUE THREAD

**Issue by MallocArray** [ansible/ansible-builder#334]
I want yamllint and ansible-lint to be available inside of my Execution Environment, so I added it to my requirements.txt file, but when the builder step runs `ansible-builder introspect --sanitize...` it strips this out from the resulting requirements.txt and is not available in the resulting EE.

I can work around this by adding a step to the append: section of additional_build_steps: to install it manually
```
    - RUN pip3 install yamllint ansible-lint
```

but this seems to go against the idea of listing all required python modules in the requirements.txt when they are removed unexpectedly by the builder stage

**Comment by Shrews** [comment]
Thanks for your report.

During sanitization, there are certain packages that are excluded because usually you do not want them in your EE. That list can be found [here](https://github.com/ansible/ansible-builder/blob/3e4a25e22f6ffdc4385b3ee4ba9e79b2efe5aa5c/ansible_builder/requirements.py#L7-L17). The `yamllint` and `ansible-lint` packages are among those.  If you run the `introspect --sanitize` command with the `-v 3` option, you should see a logging message indicating the exclusions.

There is an open request to [disable sanitization](https://github.com/ansible/ansible-builder/issues/323), which I think would help you here. Is seems that request is currently being worked on.

For the time being, you will have to continue adding the manual install step, as you demonstrated in your example.

**Comment by Shrews** [comment]
I'm going to re-open this and make it a feature request to ignore exclusions. The work being done in the issue referenced above will be to rework the requirements bits, so I'd hate to have two feature changes in a single PR.
