### ISSUE TITLE
ansible-builder CentOS 8 image dnf error

### ISSUE THREAD

**Issue by ecchong** [ansible/ansible-builder#349]
I am trying to run ansible-builder to install a rpm in the execution environment via bindep, but getting the following error 

`+ /usr/bin/dnf update -y`
`CentOS Linux 8 - AppStream                      197  B/s |  38  B     00:00    `
`Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist`

Is it because of CentOS 8 EOL and the ansible-builder image is CentOS based?  Is there a fix or plan to switch to a RHEL UBI based ansible-builder image?

**Comment by ecchong** [comment]
OK.  There is a RHEL based ansible-builder image.  I just need to specify the following in the execution-environment.yml

EE_BUILDER_IMAGE='registry.redhat.io/ansible-automation-platform-21/ansible-builder-rhel8'

Will the default CentOS 8 image be fixed?  If not it should be removed to prevent confusion.

**Comment by d5han** [comment]
I experienced the same issue. The workaround I used was cloning the ansible-builder and ansible-runner repos and building them locally. The containers consumed by builder/runner are updated, so rebuilding them results in working repositories.

```
git clone https://github.com/ansible/ansible-builder.git
cd ansible-builder; CONTAINER_ENGINE=podman make image

git clone https://github.com/ansible/ansible-runner.git
cd ansible-runner; CONTAINER_ENGINE=podman make image
```

Since this will tag the resulting images as `quay.io/ansible/ansible-builder:latest` and `quay.io/ansible/ansible-runner:latest`. I could then run `ansible-builder` like I normally would, and those local images would be used instead of pulling the stale ones.

**Comment by Shrews** [comment]
The `ansible-builder` and `ansible-runner` images are both now based off of `CentOS Stream release 8` and not `Centos 8`, which is EOL. I suspect you need to remove your local image and just pull the newer images.

**Comment by d5han** [comment]
Yep, now with the images updated I am able to run `ansible-builder` without the need for the locally built images.

Looks fixed to me.

**Comment by Shrews** [comment]
Closing per above.
