### ISSUE TITLE
Better collection & python dependency management

### ISSUE THREAD

**Issue by ryanmerolle** [ansible/ansible-builder#365]
This is Sort of related to Ansible-galaxy listing outdated collections and roles

- ansible/ansible#75632

I've noticed when I pin packages roles and collection versions, I enter into dependency hell.  It would be ideal if either:

- ansible-builder (because it's aware of a requirements.txt and a requirements.yml) recognized this before a build
- ansible-galaxy had a way to to sort this out sort of like poetry for ansible collection dependencies

I'm happy to open something in the ansible core repo if needed instead.  It just seems like with the push to ansible execution-environments and building then with ansible-builder, this sort of process should be easier.

**Comment by eqrx** [comment]
Hey :) Problem is that builder by design only calls the different package management tools. I agree that this would be nice but we the complexity would be quite high and the scope of builder would blow up. Feel free to suggest PRs on this but we currently do not see how to implement this in a maintainable manner! Thanks!
