### ISSUE TITLE
Option to use additional PKGMGR_OPTS through ansible-builder

### ISSUE THREAD

**Issue by Akasurde** [ansible/ansible-builder#418]
Feature request - Option to use PKGMGR_OPTS with Ansible Builder to disable repository using microdnf.
While creating a custom image there is no option to pass microdnf parameters.

**Comment by rseabra** [comment]
Hi,

+1 I'll let you know how we worked around this:

We created a script in order to give automate some control over this ansible-builder package, because it's really a lot more painful than it should be, specially in disconnected environments.

For this particular case we do the following:

1. have a directory per EE that we want to prepare
2. source an environments file that loads several variable to use in the script
3. two of the variables we created are DISABLEREPOS and ENABLEREPOS
4. we then use them in two sed calls to fix RUN assemble and RUN /output/install-from-bindep scripts in the ContainerFile 

`
if [ -e ./sheel-env.conf ] ; then
  . ./shell-env.conf
fi

(...)

sed -i -e "
s, RUN assemble, RUN PKGMGR_OPTS='$DISABLEREPOS $ENABLEREPOS --nodocs --setopt install_weak_deps=0' assemble,;
s, RUN /output/install-from-bindep, RUN PKGMGR_OPTS='$DISABLEREPOS $ENABLEREPOS --nodocs --setopt install_weak_deps=0' /output/install-from-bindep,;
" context/ContainerFile
`

It would be very useful that assemble and install-from-bindep extended the if -z $PKMGR_OPTS so that if it is defined it would just append it's own flags, like adding an else with PKGMGR_OPTS="$PKGMGR_OPTS --nodocs --setopt install_weak_deps=0"

This way in evolutions of ansible-builder there would be less risk of missing some new crucial option that was setup.

**Comment by Shrews** [comment]
This change shouldn't be necessary. You could just add this in the new v3 EE format:

```
additional_build_steps:
   prepend_builder: ENV PKMGR_OPTS="--whatever"
```

We have the option to set PKMGR in the EE because that is used directly by the code building the Containerfile. That code cannot programmatically deteremine which pkg manager is present, unlike the `assemble` script, which can run inside the container. I don't think we should try to expose the other script env options with an EE equivalent.

**Comment by Shrews** [comment]
> This change shouldn't be necessary. You could just add this in the new v3 EE format:

Oops, this comment was meant for the PR implementation...

**Comment by Akasurde** [comment]
Closing as per https://github.com/ansible/ansible-builder/issues/418#issuecomment-1521706798. Thanks,
