### ISSUE TITLE
supress warning about tmp build dir not being in collections path on build host

### ISSUE THREAD

**Issue by kdelee** [ansible/ansible-builder#42]
In the output of `ansible-builder build` I see:

```
  ansible-galaxy collection install -r reqs.yml -p /tmp/ansible_builder_jn54s8dn
[WARNING]: The specified collections path '/tmp/ansible_builder_jn54s8dn' is not part of the
configured Ansible collections paths    
'/home/elijah/.ansible/collections:/usr/share/ansible/collections'. The installed collection
won't be picked up in an Ansible run.  
```

Because ` /tmp/ansible_builder_jn54s8dn` is not on my local machine's ansible collection path, but that is normal -- it is not meant for execution on my local machine, rather it is going to get placed in the collections path inside the container.

This warning is a bit confusing so would be good to supress it. I bet there is an env var we can set when calling `ansible-galaxy`

**Comment by AlanCoding** [comment]
Example of the current command:

```
RUN ansible-galaxy collection install -r /build/requirements.yml --collections-path /usr/share/ansible/collections
```

This is only ran once, and it doesn't produce the error because `/usr/share/ansible/collections` is, by default, one of the collection paths.

We used to install collections separately to a `/tmp` folder, but @shanemcd developed a more elegant solution for that, and this practice was removed.

Closing now, because that refactor eliminated this.
