### ISSUE TITLE
ERROR: Could not install packages due to an EnvironmentError: [Errno 21] Is a directory: '/usr/local/requirements.txt'

### ISSUE THREAD

**Issue by Akasurde** [ansible/ansible-builder#444]
_From @Alexxio1981 on Jan 23, 2023 10:52_

##### SUMMARY
Failed to build an EE with Ansible Automation Platform

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.vmware 

##### ANSIBLE VERSION
Ansible Automation Platform Controller 4.2.1

##### COLLECTION VERSION
Collection version 3.2.0

##### OS / ENVIRONMENT
Red Hat Enterprise Linux 8.7 (Ootpa)

_Copied from original issue: ansible/ansible#1601_

**Comment by Akasurde** [comment]
_From @Akasurde on Jan 23, 2023 10:59_

@Alexxio1981 Thanks for reporting this issue. Can you please provide steps to reproduce this issue?

**Comment by Akasurde** [comment]
_From @Alexxio1981 on Jan 23, 2023 11:04_

Hello,
here the file for building EE:

execution-environment.yml
```
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-22/ee-29-rhel8:latest'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

requirements.txt

botocore>=1.18.0
boto3>=1.15.0
boto>=2.49.0

requirements.yml

---
collections:
  - name: community.vmware
```

Then this command was launched:

```
ansible-builder build -t vmware_community_ee -v 3
```

**Comment by Akasurde** [comment]
@Alexxio1981 I migrated this issue here since it is related to ansible-builder rather than community.vmware.

**Comment by Akasurde** [comment]
Reproducer logs [444.log](https://github.com/ansible/ansible-builder/files/10479339/444.log)

**Comment by sivel** [comment]
For some reason that `ee-29-rhel8` contains a directory at `/usr/local/requirements.txt` likely errantly, that contains a `requirements.txt` with the following contents:

```
jinja2
kubernetes ~= 11.0.0
python-string-utils
ruamel.yaml >= 0.15
six
```

In any case, even if it were a file and not a directory, it seems there may still be a problem.

The problem occurs due to the `vapi_runtime` package included at https://github.com/vmware/vsphere-automation-sdk-python/blob/master/lib/vapi-runtime/vapi_runtime-2.37.0-py2.py3-none-any.whl

```shell
bash-4.4# curl -sLo vapi_runtime-2.37.0-py2.py3-none-any.whl 'https://github.com/vmware/vsphere-automation-sdk-python/blob/master/lib/vapi-runtime/vapi_runtime-2.37.0-py2.py3-none-any.whl?raw=true'
bash-4.4# pip3 install --no-deps vapi_runtime-2.37.0-py2.py3-none-any.whl
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Processing ./vapi_runtime-2.37.0-py2.py3-none-any.whl
Installing collected packages: vapi-runtime
ERROR: Could not install packages due to an EnvironmentError: [Errno 21] Is a directory: '/usr/local/requirements.txt'
```

That `vapi_runtime` is an installed dep of the `vsphere-automation-sdk-python` package:

https://github.com/vmware/vsphere-automation-sdk-python/blob/88d1c65407004cff326daeaa33b0b4e317142b47/setup.py#L17

If we look at the contents of that `vapi_runtime-2.37.0-py2.py3-none-any.whl` file we can see these data files:

```
  inflating: vapi_runtime-2.37.0.data/data/requirements.txt
  inflating: vapi_runtime-2.37.0.data/data/test-requirements.txt
```

Due to these data files being present, they are attempted to be installed in `/usr/local` since we're just installing globally, which conflicts with the directory that is being distributed by the EE base image.

I guess someone can do some research into what that `/usr/local/requirements.txt/requirements.txt` file is for, but I also question whether the `vapi_runtime-2.37.0-py2.py3-none-any.whl` should be including it's `requirements.txt` and `test-requirements.txt` as data files.

**Comment by sivel** [comment]
I did a little more investigation, and found that the `/usr/local/requirements.txt/requirements.txt` file is actually owned by the `openshift` python package:

```shell
bash-4.4# pip3 uninstall openshift
Found existing installation: openshift 0.11.2
Uninstalling openshift-0.11.2:
  Would remove:
    /usr/local/bin/openshift-ansible-gen
    /usr/local/lib/python3.8/site-packages/openshift-0.11.2.dist-info/*
    /usr/local/lib/python3.8/site-packages/openshift/*
    /usr/local/lib/python3.8/site-packages/scripts/*
    /usr/local/requirements.txt/requirements.txt
Proceed (y/n)?
```

So it's not as much of a problem in the base EE build process, just 2 incompatible packages that are both trying to install a generically named file/directory as a data file, which cause issues.

**Comment by Shrews** [comment]
Thanks for the in-depth triage @sivel!

Neither of the problem packages (openshift and vapi_runtime) are something we have control over in `ansible-builder`. Ideally, separate issues should be filed with the owners of those packages.

**Comment by Akasurde** [comment]
As per the above comment. I am closing this issue as won't fix.

**Comment by ansiblejunky** [comment]
I just hit this problem, and adding the following to the prepend section of the exec-env.yml worked for me:
```
RUN pip3 uninstall -y openshift
```
