### ISSUE TITLE
[RFE]  Allow the user to specify a default tag in the `execution-environment.yml` 

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-builder#523]
If added as an optional key, to replace the default, it would allow for a "right-click" build without having to prompt the user in VSCode.

This would also have the side benefit of identifying which EE a  given `execution-environment.yml` file was for as today, there is no metadata within the execution-environment.yml indicating the name of the EE being built. 

Related: https://github.com/ansible/vscode-ansible/issues/878

**Comment by nitzmahone** [comment]
Interesting idea- basically just providing an EE def directive to override the default `localhost/ansible-execution-env` for `build` calls where a `-t` wasn't passed?  I haven't seen how the VSCode plugin is actually invoking the build- is it generating an `ansible-builder build` command, or is it doing a `create` and directly invoking a specific build runtime?

IIRC this would also be a no-op for `create` cases, since TMK there's no `Containerfile` directive to specify a default tag, but that's fine.

+1 from me, probably for 3.1 though at this point :wink:

**Comment by cidrblock** [comment]
NP, the extension would just create a command and run it for the user, so we won't have to prompt for it
